### ISSUE TITLE
Quick fixes

### ISSUE THREAD

**Issue by vXBaKeRXv** [PoomSmart/EmojiSkinPrefs#1]
I still cant compile this on theos anymore for some reason...
Wish I could just compile it and make these touches on my own without having to bug you on it. 

Just needs few changes if you can:
Save button on navbar doesn't respring/refresh the device
SkinKeyOff code/cell can be dropped, I agree. 
UpdateToneOff doesn't work.. forgot what it does. Keep tweak simple and Remove ?

Skins for like Handshake and Families seem to be a Unicode spec for U12 Drafts.

**Comment by PoomSmart** [comment]
- Get yourself the latest theos build.
- Respringing is not mandatory. Changing in the skin color takes an effect rather immediately.
- Dropping SkinKeyOff, noted.
- UpdateToneOff itself already has the confusing name. Just remove.
- EmojiLibrary will take care of such unicode updates.

**Comment by PoomSmart** [comment]
You should use the official build of theos (theos/theos) rather than individual’s.

Also make sure to update Xcode to the latest version.

**Comment by PoomSmart** [comment]
Show the exact compilation error here.

**Comment by vXBaKeRXv** [comment]
The same error shown in shots exceeds the error limit -
https://i.imgur.com/iLt8aKP.png
https://i.imgur.com/07ELjBG.png

**Comment by PoomSmart** [comment]
The compiler version is old. The quickest way to fix is to remove any `<... *>` out of the method types of any affected files.
For example:
`(NSArray <NSString *> *)` to `(NSArray *)`

**Comment by vXBaKeRXv** [comment]
Thanks for the info-help! I wasn't sure if that was normal to do that. 

I updated it from scratch using the main theos on github in 7-20-2016.  
Running the command in terminal $THEOS/bin/update-theos and output says its up to date. 
https://github.com/theos/theos/wiki/Installation 

Stuck on one last error with Makefile I think ?
https://i.imgur.com/keK3HFo.png

Do I need to add EmojiLibrary.dylib to project and include include below. Hmmm
EmojiSkinPrefs_LDFLAGS = -Llib -lEmojiLibrary

**Comment by PoomSmart** [comment]
You somewhat answered your question.

**Comment by PoomSmart** [comment]
Because I use macOS as a platform and the most recent version of theos.

**Comment by vXBaKeRXv** [comment]
Hahaha OK! I will check into the theos <... *> again later on because its a pain to setup. Thanks once again POOM 

Do you want/have time for a tweak fix job? willing to send you little money for the help.
Got nothing on 10.x so I cant tinker with problems. 
 
Change text or use a glyph logo on the KB space key (SpaceKey Tweak).
1 - key.displayStringImage is not loading custom UIImage anymore.
2 - key.displayString is showing that black filled emoji.
